dist: xenial
sudo: false

language: node_js
node_js:
  - '14.15'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
    chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install
  - npm install -g @angular/cli
  - npm install -g @angular-devkit/build-angular
  - npm install -g karma-cli
  - npm install -g firebase-tools
  - npm install -g codecov

script:
  - npm run build
  - ng test --browsers=ChromeHeadlessNoSandbox --codeCoverage=true --watch=false || true
  
after_script:
  - codecov --disable=gcov -t 263d68c4-2769-4380-a69a-be315a5bc38a
  - firebase deploy --token 1//0gI0keGyx6siQCgYIARAAGBASNwF-L9IrwCAxngVhsqfPZyd6KOMVzy6-AzNRfKlggvpbG1VluALSJFVU4i8by0bIKAhgC3SEcyc
  
